### ISSUE TITLE
rosjava_messages failing to build on Debian Jessie amd64

### ISSUE THREAD

**Issue by tfoote** [rosjava/rosjava_messages#29]
I'm not sure why this is happening but it appears that there's an issue with the build on Jessie amd64 for kinetic. 

http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__rosjava_messages__debian_jessie_amd64__binary/32/consoleFull

It looks to be trying to download gradle inside the build and it's failing on a certificate error: 
```
[100%] Compiling rosjava message artifacts for [std_msgs rosgraph_msgs std_srvs rosjava_test_msgs actionlib_msgs common_msgs diagnostic_msgs geometry_msgs nav_msgs sensor_msgs shape_msgs stereo_msgs trajectory_msgs visualization_msgs tf2_msgs ar_track_alvar_msgs uuid_msgs yocs_msgs concert_msgs concert_service_msgs gateway_msgs rocon_app_manager_msgs rocon_device_msgs rocon_interaction_msgs rocon_service_pair_msgs rocon_std_msgs rocon_tutorial_msgs world_canvas_msgs scheduler_msgs move_base_msgs map_store roscpp]
/tmp/binarydeb/ros-kinetic-rosjava-messages-0.3.0/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh /usr/bin/python /opt/ros/kinetic/share/genjava/cmake/../../../lib/genjava/genjava_message_artifacts --avoid-rebuilding -o /tmp/binarydeb/ros-kinetic-rosjava-messages-0.3.0/obj-x86_64-linux-gnu -p std_msgs rosgraph_msgs std_srvs rosjava_test_msgs actionlib_msgs common_msgs diagnostic_msgs geometry_msgs nav_msgs sensor_msgs shape_msgs stereo_msgs trajectory_msgs visualization_msgs tf2_msgs ar_track_alvar_msgs uuid_msgs yocs_msgs concert_msgs concert_service_msgs gateway_msgs rocon_app_manager_msgs rocon_device_msgs rocon_interaction_msgs rocon_service_pair_msgs rocon_std_msgs rocon_tutorial_msgs world_canvas_msgs scheduler_msgs move_base_msgs map_store roscpp
Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip

Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:44)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error

```
The full traceback is much longer and you can find it here: https://gist.github.com/tfoote/8c8e77e8cbb8d50690d0b13cbfecef13

It's quite possible that this is a regression due to a security release: https://packages.debian.org/search?keywords=openjdk-7-jre and we need to update something on the build farm. But I'm ticketing it here for now. 

I found a few other related reports:
- https://github.com/ether-camp/ethereum-harmony/issues/33
- https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2479
- https://forums.aws.amazon.com/thread.jspa?threadID=230048
- https://jira.atlassian.com/browse/BSERV-6955

It looks like the jessie version of openjdk might be hitting these issues.

**Comment by adamantivm** [comment]
Thank you @tfoote. This is unfortunate, but it does look like a regression on the JDK like you pointed out. This is going to affect far more than the build farm. Here is another reported rosjava incident most likely due to the same: https://github.com/rosjava/rosjava_core/issues/252

**Comment by tfoote** [comment]
This is now failing on Ubuntu Trusty too: eg: http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__rosjava_messages__ubuntu_trusty_amd64__binary/92/console
